import { ArrowRight, Heart, Sparkles, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { PageHero, SectionHeading } from "@/components/PageBits";
import PublicLayout from "@/components/PublicLayout";

const values = [{ icon: Heart, title: "Presence before performance", copy: "We gather to meet with God, not to impress one another." }, { icon: UsersRound, title: "People are the ministry", copy: "Every person is worthy of welcome, care, and meaningful community." }, { icon: Sparkles, title: "Faith for real life", copy: "We open Scripture and pray with the confidence that Jesus changes everyday life." }];

export default function About() {
  return <PublicLayout><PageHero eyebrow="Who we are" title="A parish family with room for you." copy="RCCG The Almighty Parish is a local church family in Ibadan, Nigeria. We are committed to worship, the Word, prayer, and a life that reflects the love of Christ." /><section className="container py-20 sm:py-28"><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="eyebrow text-[#0b4ab8]">Our heart</p><h2 className="display mt-5 text-5xl leading-[0.95] text-[#10213e]">Faith that takes root and bears fruit.</h2></div><div className="text-base leading-8 text-slate-600"><p>At TAP Church, we believe church is not an event to observe but a family to join. We make space for worship that lifts our eyes, teaching that strengthens our steps, and relationships that keep us growing.</p><p className="mt-5">As part of The Redeemed Christian Church of God, we desire to see lives renewed by Christ and our city served with humility, hope, and joy.</p><Link href="/visit" className="tap-button mt-8 inline-flex items-center gap-2 rounded-full bg-[#0b4ab8] px-5 py-3 text-sm font-extrabold text-white">Plan a Visit<ArrowRight className="h-4 w-4" /></Link></div></div></section><section className="border-y border-slate-200 bg-white py-20 sm:py-28"><div className="container"><SectionHeading eyebrow="What shapes us" title="The kind of community we are becoming." /><div className="mt-12 grid gap-4 md:grid-cols-3">{values.map(value => <article key={value.title} className="rounded-[1.4rem] border border-slate-200 p-6"><value.icon className="h-6 w-6 text-[#0b4ab8]" /><h3 className="mt-10 text-lg font-extrabold text-[#10213e]">{value.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{value.copy}</p></article>)}</div></div></section></PublicLayout>;
}
