import PublicLayout from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { Link } from "wouter";
import { useEffect, useState } from "react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

export default function Account() {
  const { user, loading, logout } = useAuth();
  if (loading) return <PublicLayout><div className="container py-24 text-sm font-bold text-slate-500">Loading account…</div></PublicLayout>;
  if (!user) return <PublicLayout><section className="container py-24"><h1 className="display text-5xl text-[#10213e]">Account access</h1><p className="mt-5 text-slate-600">Sign in or create a member account to continue.</p><Link href="/sign-in" className="tap-button mt-7 inline-flex rounded-full bg-[#0b4ab8] px-5 py-3 text-sm font-extrabold text-white">Sign in</Link></section></PublicLayout>;
  return <PublicLayout><AccountWorkspace user={user} logout={logout} /></PublicLayout>;
}

function AccountWorkspace({ user, logout }: { user: { name: string; email: string; role: string }; logout: () => void }) {
  const [name, setName] = useState(user.name); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const utils = trpc.useUtils();
  useEffect(() => setName(user.name), [user.name]);
  const updateName = trpc.account.profile.updateName.useMutation({ onSuccess: () => { void utils.auth.me.invalidate(); toast.success("Your name has been updated."); }, onError: error => toast.error(error.message) });
  const changePassword = trpc.account.profile.changePassword.useMutation({ onSuccess: () => { setCurrentPassword(""); setNewPassword(""); toast.success("Your password has been updated."); }, onError: error => toast.error(error.message) });
  const staff = user.role !== "member";
  return <section className="container py-20 sm:py-28"><p className="eyebrow text-[#0b4ab8]">TAP account</p><h1 className="display mt-4 text-5xl text-[#10213e]">Welcome, {user.name}.</h1><div className="mt-8 grid max-w-4xl gap-5 md:grid-cols-2"><section className="rounded-[1.5rem] border border-slate-200 bg-white p-7"><p className="text-sm font-extrabold text-[#10213e]">Account status</p><p className="mt-3 text-sm leading-7 text-slate-600">You are registered as a <strong>{user.role.replaceAll("_", " ")}</strong>. {staff ? "Your approved staff workspace is available below." : "Your member account is active."}</p><p className="mt-4 text-xs font-bold text-slate-500">{user.email}</p>{staff && <Link href="/admin" className="tap-button mt-6 inline-flex rounded-full bg-[#0b4ab8] px-5 py-3 text-sm font-extrabold text-white">Open staff workspace</Link>}<Button variant="outline" onClick={() => void logout()} className="mt-6 block rounded-full">Sign out</Button></section><section className="rounded-[1.5rem] border border-slate-200 bg-white p-7"><p className="text-sm font-extrabold text-[#10213e]">Personal details</p><form className="mt-5 grid gap-3" onSubmit={event => { event.preventDefault(); updateName.mutate({ name }); }}><label className="grid gap-1.5 text-xs font-bold text-slate-600">Display name<input required value={name} onChange={event => setName(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm" /></label><Button disabled={updateName.isPending || name.trim() === user.name} className="h-11 rounded-xl bg-[#0b4ab8] text-xs font-extrabold">Save name</Button></form></section><section className="rounded-[1.5rem] border border-slate-200 bg-white p-7 md:col-span-2"><p className="text-sm font-extrabold text-[#10213e]">Change password</p><p className="mt-2 text-sm leading-6 text-slate-600">Use at least 10 characters and keep your new password private.</p><form className="mt-5 grid gap-3 sm:grid-cols-3" onSubmit={event => { event.preventDefault(); changePassword.mutate({ currentPassword, newPassword }); }}><label className="grid gap-1.5 text-xs font-bold text-slate-600">Current password<input required type="password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm" /></label><label className="grid gap-1.5 text-xs font-bold text-slate-600">New password<input required minLength={10} type="password" value={newPassword} onChange={event => setNewPassword(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm" /></label><Button disabled={changePassword.isPending || !currentPassword || newPassword.length < 10} className="mt-auto h-11 rounded-xl bg-[#0b4ab8] text-xs font-extrabold">Update password</Button></form></section></div></section>;
}
