import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { QueryError } from "@/components/PageBits";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CalendarDays, FilePlus2, Images, Loader2, Megaphone, Newspaper, Pencil, Plus, Trash2, UsersRound, Video } from "lucide-react";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

type Tab = "overview" | "events" | "sermons" | "news" | "ministries" | "announcements" | "media";
type Row = Record<string, unknown> & { id: string };

const tabItems: Array<{ id: Tab; label: string; icon: typeof CalendarDays }> = [
  { id: "overview", label: "Overview", icon: FilePlus2 },
  { id: "events", label: "Events", icon: CalendarDays },
  { id: "sermons", label: "Sermons", icon: Video },
  { id: "news", label: "News", icon: Newspaper },
  { id: "ministries", label: "Ministries", icon: UsersRound },
  { id: "announcements", label: "Announcements", icon: Megaphone },
  { id: "media", label: "Media", icon: Images },
];

const inputClass = "mt-1.5 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none transition-colors focus:border-[#0b4ab8]";
const textareaClass = "mt-1.5 min-h-24 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none transition-colors focus:border-[#0b4ab8]";
const labelClass = "text-xs font-extrabold uppercase tracking-[0.11em] text-slate-500";
const toInputDate = (value: unknown) => value ? new Date(value as Date).toISOString().slice(0, 16) : "";

export default function Admin() {
  return <DashboardLayout><AdminWorkspace /></DashboardLayout>;
}

function AdminWorkspace() {
  const { user, loading } = useAuth();
  const role = user?.role;
  const isStaff = !!role && ["worker", "ministry_leader", "editor", "admin", "master_admin"].includes(role);
  const canEdit = !!role && ["editor", "admin", "master_admin"].includes(role);
  const [tab, setTab] = useState<Tab>("overview");
  const [editing, setEditing] = useState<string | null>(null);
  const { data: summary, isLoading: summaryLoading, isError: summaryError, refetch: refetchSummary } = trpc.content.admin.summary.useQuery(undefined, { enabled: isStaff });
  const { data: all, isLoading: contentLoading, isError: contentError, refetch: refetchContent } = trpc.content.admin.all.useQuery(undefined, { enabled: isStaff });

  if (loading) return <div className="grid min-h-[50vh] place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[#0b4ab8]" /></div>;
  if (!isStaff) return <section className="mx-auto max-w-2xl py-16"><p className="eyebrow text-[#0b4ab8]">TAP staff workspace</p><h1 className="display mt-4 text-5xl leading-[0.95] text-[#10213e]">This area is for approved staff.</h1><p className="mt-5 text-sm leading-7 text-slate-600">Your account is signed in, but it has not yet been assigned a staff role. An administrator can promote accounts to worker, ministry leader, editor, or administrator access from the database management panel.</p></section>;
  if (summaryError || contentError) return <section className="mx-auto max-w-2xl py-16"><QueryError label="The staff workspace could not load its latest content." retry={() => { void refetchSummary(); void refetchContent(); }} /></section>;

  const title = tabItems.find(item => item.id === tab)?.label ?? "Overview";
  const rows = tab === "events" ? all?.events : tab === "sermons" ? all?.sermons : tab === "news" ? all?.posts : tab === "ministries" ? all?.ministries : tab === "announcements" ? all?.announcements : tab === "media" ? all?.media : [];
  const selected = editing ? (rows as Row[] | undefined)?.find(row => row.id === editing) : undefined;

  return <section className="mx-auto max-w-6xl py-5 sm:py-8"><div className="flex flex-col justify-between gap-5 border-b border-slate-200 pb-7 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#0b4ab8]">TAP staff workspace</p><h1 className="display mt-3 text-4xl leading-none text-[#10213e]">{title}</h1><p className="mt-3 text-sm text-slate-500">Signed in as {user?.name ?? "Staff member"} · {role?.replace("_", " ")}</p></div><a href="/" className="text-xs font-extrabold text-[#0b4ab8]">View public site ↗</a></div>
    <div className="mt-6 flex gap-2 overflow-x-auto pb-1">{tabItems.map(item => <button key={item.id} onClick={() => { setTab(item.id); setEditing(null); }} className={`tap-button inline-flex shrink-0 items-center gap-2 rounded-full px-3.5 py-2 text-xs font-extrabold ${tab === item.id ? "bg-[#0b4ab8] text-white" : "border border-slate-200 bg-white text-slate-600 hover:border-[#0b4ab8] hover:text-[#0b4ab8]"}`}><item.icon className="h-3.5 w-3.5" />{item.label}</button>)}</div>
    {tab === "overview" ? <Overview summary={summary} loading={summaryLoading} setTab={setTab} /> : <ContentWorkspace tab={tab} canEdit={canEdit} loading={contentLoading} rows={(rows ?? []) as Row[]} selected={selected} onEdit={setEditing} onCancel={() => setEditing(null)} />}
  </section>;
}

function Overview({ summary, loading, setTab }: { summary?: { sermons: number; events: number; posts: number; media: number; ministries: number }; loading: boolean; setTab: (tab: Tab) => void }) {
  const cards = [{ label: "Sermons", count: summary?.sermons ?? 0, tab: "sermons" as Tab, icon: Video }, { label: "Events", count: summary?.events ?? 0, tab: "events" as Tab, icon: CalendarDays }, { label: "News posts", count: summary?.posts ?? 0, tab: "news" as Tab, icon: Newspaper }, { label: "Media assets", count: summary?.media ?? 0, tab: "media" as Tab, icon: Images }, { label: "Ministry pages", count: summary?.ministries ?? 0, tab: "ministries" as Tab, icon: UsersRound }];
  return <div className="mt-8"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(card => <button key={card.label} onClick={() => setTab(card.tab)} className="tap-button rounded-2xl border border-slate-200 bg-white p-5 text-left hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-lg hover:shadow-blue-900/5"><card.icon className="h-5 w-5 text-[#0b4ab8]" /><p className="mt-7 text-3xl font-extrabold text-[#10213e]">{loading ? "—" : card.count}</p><p className="mt-1 text-xs font-bold text-slate-500">{card.label}</p></button>)}</div><div className="mt-8 rounded-[1.4rem] bg-[#eaf2ff] p-7"><p className="eyebrow text-[#0b4ab8]">Editorial workflow</p><h2 className="display mt-4 text-4xl leading-[0.95] text-[#10213e]">Publish with accuracy.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-600">Every public page reads from this content workspace. Draft an item, check its details, then mark it published only when it is ready for the parish website.</p></div></div>;
}

function ContentWorkspace({ tab, canEdit, loading, rows, selected, onEdit, onCancel }: { tab: Exclude<Tab, "overview">; canEdit: boolean; loading: boolean; rows: Row[]; selected?: Row; onEdit: (id: string | null) => void; onCancel: () => void }) {
  const title = tab === "news" ? "article" : tab === "media" ? "media asset" : tab.slice(0, -1);
  return <div className="mt-8 grid gap-7 xl:grid-cols-[1fr_1.08fr]"><div><div className="flex items-center justify-between"><p className="text-sm font-extrabold text-[#10213e]">Published and draft content</p>{canEdit && <button onClick={() => onEdit(null)} className="tap-button inline-flex items-center gap-1.5 rounded-full bg-[#0b4ab8] px-3.5 py-2 text-xs font-extrabold text-white"><Plus className="h-3.5 w-3.5" />New {title}</button>}</div><div className="mt-4 space-y-3">{loading ? <div className="h-32 animate-pulse rounded-2xl bg-slate-200" /> : rows.length ? rows.map(row => <ContentRow key={row.id} row={row} onEdit={() => onEdit(row.id)} canEdit={canEdit} tab={tab} />) : <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-6"><p className="font-extrabold text-[#10213e]">No {tab} created yet.</p><p className="mt-2 text-sm leading-6 text-slate-500">Use the editor to create the first {title} for the public site.</p></div>}</div></div><div className="xl:sticky xl:top-24 xl:self-start">{canEdit ? <Editor tab={tab} selected={selected} onDone={onCancel} /> : <div className="rounded-[1.4rem] border border-slate-200 bg-white p-7"><p className="font-extrabold text-[#10213e]">View-only staff access</p><p className="mt-3 text-sm leading-7 text-slate-600">Your role can review content but cannot publish or change it. Ask an editor or administrator for publishing access.</p></div>}</div></div>;
}

function ContentRow({ row, onEdit, canEdit, tab }: { row: Row; onEdit: () => void; canEdit: boolean; tab: Tab }) {
  const title = String(row.title ?? "Untitled item");
  const status = row.isPublished === true || row.isActive === true ? "Published" : "Draft";
  const DeleteButton = () => <DeleteContent id={row.id} tab={tab} />;
  return <article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex gap-4"><div className="min-w-0 flex-1"><p className="truncate font-extrabold text-[#10213e]">{title}</p><p className="mt-1 text-xs font-bold text-slate-500">{String(row.slug ?? row.category ?? row.mediaType ?? "TAP content")}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[0.62rem] font-extrabold ${status === "Published" ? "bg-lime-100 text-lime-800" : "bg-slate-100 text-slate-500"}`}>{status}</span></div>{canEdit && <div className="mt-4 flex gap-2"><button onClick={onEdit} className="tap-button inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-extrabold text-slate-600 hover:border-[#0b4ab8] hover:text-[#0b4ab8]"><Pencil className="h-3.5 w-3.5" />Edit</button><DeleteButton /></div>}</article>;
}

function DeleteContent({ id, tab }: { id: string; tab: Tab }) {
  const utils = trpc.useUtils();
  const [failure, setFailure] = useState<string | null>(null);
  const mutation = tab === "events" ? trpc.content.events.delete.useMutation() : tab === "sermons" ? trpc.content.sermons.delete.useMutation() : tab === "news" ? trpc.content.posts.delete.useMutation() : tab === "ministries" ? trpc.content.ministries.delete.useMutation() : tab === "announcements" ? trpc.content.announcements.delete.useMutation() : trpc.content.media.delete.useMutation();
  const remove = () => mutation.mutate({ id }, { onSuccess: () => { setFailure(null); void utils.content.admin.all.invalidate(); void utils.content.admin.summary.invalidate(); toast.success("Content removed."); }, onError: error => { setFailure(error.message); toast.error(error.message); } });
  return <div className="space-y-2"><button onClick={remove} disabled={mutation.isPending} className="tap-button inline-flex items-center gap-1.5 rounded-lg border border-rose-100 px-3 py-2 text-xs font-extrabold text-rose-600 hover:bg-rose-50 disabled:opacity-50"><Trash2 className="h-3.5 w-3.5" />Delete</button>{failure && <p role="alert" className="max-w-xs text-xs leading-5 text-rose-700">Delete failed. {failure} <button onClick={remove} className="font-extrabold underline">Retry</button></p>}</div>;
}

function Editor({ tab, selected, onDone }: { tab: Exclude<Tab, "overview">; selected?: Row; onDone: () => void }) {
  if (tab === "events") return <EventEditor key={selected?.id ?? "new"} selected={selected} onDone={onDone} />;
  if (tab === "sermons") return <SermonEditor key={selected?.id ?? "new"} selected={selected} onDone={onDone} />;
  if (tab === "news") return <PostEditor key={selected?.id ?? "new"} selected={selected} onDone={onDone} />;
  if (tab === "ministries") return <MinistryEditor key={selected?.id ?? "new"} selected={selected} onDone={onDone} />;
  if (tab === "announcements") return <AnnouncementEditor key={selected?.id ?? "new"} selected={selected} onDone={onDone} />;
  return <MediaEditor onDone={onDone} />;
}

function FormShell({ title, children, onCancel, error }: { title: string; children: React.ReactNode; onCancel: () => void; error?: string | null }) { return <div className="rounded-[1.4rem] border border-slate-200 bg-white p-6 sm:p-7"><div className="flex items-center justify-between"><p className="font-extrabold text-[#10213e]">{title}</p><button type="button" onClick={onCancel} className="text-xs font-extrabold text-slate-500 hover:text-[#0b4ab8]">Clear form</button></div>{error && <div role="alert" className="mt-5 rounded-xl border border-rose-100 bg-rose-50 p-4 text-sm text-rose-800"><p className="font-extrabold">Your draft was not published.</p><p className="mt-1 leading-6">{error} Your entries are still here; correct any details and submit again.</p></div>}<div className="mt-6">{children}</div></div>; }

function useEditorFailure() {
  const [failure, setFailure] = useState<string | null>(null);
  return {
    failure,
    fail: (error: { message: string }) => {
      setFailure(error.message);
      toast.error(error.message);
    },
  };
}

function EventEditor({ selected, onDone }: { selected?: Row; onDone: () => void }) {
  const utils = trpc.useUtils(); const save = trpc.content.events.save.useMutation(); const { failure, fail } = useEditorFailure();
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); save.mutate({ id: selected?.id, values: { title: String(f.get("title")), slug: String(f.get("slug")), excerpt: String(f.get("excerpt")), description: String(f.get("description")), location: String(f.get("location")), startsAt: new Date(String(f.get("startsAt"))), endsAt: f.get("endsAt") ? new Date(String(f.get("endsAt"))) : null, registrationUrl: String(f.get("registrationUrl") || ""), coverImageUrl: String(f.get("coverImageUrl") || ""), isPublished: f.get("isPublished") === "on" } }, { onSuccess: () => { void utils.content.admin.all.invalidate(); void utils.content.admin.summary.invalidate(); toast.success("Event saved."); onDone(); }, onError: fail }); };
  return <FormShell title={selected ? "Edit event" : "New event"} onCancel={onDone} error={failure}><form onSubmit={submit} className="grid gap-4"><Field label="Title"><input name="title" required defaultValue={String(selected?.title ?? "")} className={inputClass} /></Field><Field label="URL slug"><input name="slug" required defaultValue={String(selected?.slug ?? "")} placeholder="e.g. worship-night" className={inputClass} /></Field><Field label="Excerpt"><textarea name="excerpt" required defaultValue={String(selected?.excerpt ?? "")} className={textareaClass} /></Field><Field label="Full description"><textarea name="description" required defaultValue={String(selected?.description ?? "")} className={textareaClass} /></Field><Field label="Location"><input name="location" required defaultValue={String(selected?.location ?? "Ibadan, Nigeria")} className={inputClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Starts"><input name="startsAt" type="datetime-local" required defaultValue={toInputDate(selected?.startsAt)} className={inputClass} /></Field><Field label="Ends"><input name="endsAt" type="datetime-local" defaultValue={toInputDate(selected?.endsAt)} className={inputClass} /></Field></div><Field label="Registration link"><input name="registrationUrl" type="url" defaultValue={String(selected?.registrationUrl ?? "")} className={inputClass} /></Field><PublishToggle checked={selected?.isPublished === true} /><SaveButton pending={save.isPending} label="Save event" /></form></FormShell>;
}

function SermonEditor({ selected, onDone }: { selected?: Row; onDone: () => void }) {
  const utils = trpc.useUtils(); const save = trpc.content.sermons.save.useMutation();
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); save.mutate({ id: selected?.id, values: { title: String(f.get("title")), slug: String(f.get("slug")), summary: String(f.get("summary")), speaker: String(f.get("speaker")), series: String(f.get("series")), videoProvider: String(f.get("videoProvider")) as "youtube" | "vimeo" | "none", videoId: String(f.get("videoId") || ""), sermonNotesTitle: String(f.get("sermonNotesTitle") || ""), sermonNotesUrl: String(f.get("sermonNotesUrl") || ""), coverImageUrl: "", publishedAt: f.get("publishedAt") ? new Date(String(f.get("publishedAt"))) : null, isPublished: f.get("isPublished") === "on" } }, { onSuccess: () => { void utils.content.admin.all.invalidate(); void utils.content.admin.summary.invalidate(); toast.success("Sermon saved."); onDone(); }, onError: error => toast.error(error.message) }); };
  return <FormShell title={selected ? "Edit sermon" : "New sermon"} onCancel={onDone} error={save.error?.message}><form onSubmit={submit} className="grid gap-4"><Field label="Title"><input name="title" required defaultValue={String(selected?.title ?? "")} className={inputClass} /></Field><Field label="URL slug"><input name="slug" required defaultValue={String(selected?.slug ?? "")} className={inputClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Speaker"><input name="speaker" required defaultValue={String(selected?.speaker ?? "")} className={inputClass} /></Field><Field label="Series"><input name="series" required defaultValue={String(selected?.series ?? "")} className={inputClass} /></Field></div><Field label="Message summary"><textarea name="summary" required defaultValue={String(selected?.summary ?? "")} className={textareaClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Video provider"><select name="videoProvider" defaultValue={String(selected?.videoProvider ?? "none")} className={inputClass}><option value="none">No video yet</option><option value="youtube">YouTube</option><option value="vimeo">Vimeo</option></select></Field><Field label="YouTube/Vimeo video ID"><input name="videoId" defaultValue={String(selected?.videoId ?? "")} className={inputClass} /></Field></div><Field label="Sermon notes title"><input name="sermonNotesTitle" defaultValue={String(selected?.sermonNotesTitle ?? "")} className={inputClass} /></Field><Field label="Sermon notes URL"><input name="sermonNotesUrl" type="url" defaultValue={String(selected?.sermonNotesUrl ?? "")} className={inputClass} /></Field><Field label="Publish date"><input name="publishedAt" type="datetime-local" defaultValue={toInputDate(selected?.publishedAt)} className={inputClass} /></Field><PublishToggle checked={selected?.isPublished === true} /><SaveButton pending={save.isPending} label="Save sermon" /></form></FormShell>;
}

function PostEditor({ selected, onDone }: { selected?: Row; onDone: () => void }) {
  const utils = trpc.useUtils(); const save = trpc.content.posts.save.useMutation();
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); save.mutate({ id: selected?.id, values: { title: String(f.get("title")), slug: String(f.get("slug")), excerpt: String(f.get("excerpt")), body: String(f.get("body")), category: String(f.get("category")), coverImageUrl: "", authorName: String(f.get("authorName")), publishedAt: f.get("publishedAt") ? new Date(String(f.get("publishedAt"))) : null, isPublished: f.get("isPublished") === "on" } }, { onSuccess: () => { void utils.content.admin.all.invalidate(); void utils.content.admin.summary.invalidate(); toast.success("Article saved."); onDone(); }, onError: error => toast.error(error.message) }); };
  return <FormShell title={selected ? "Edit article" : "New article"} onCancel={onDone} error={save.error?.message}><form onSubmit={submit} className="grid gap-4"><Field label="Title"><input name="title" required defaultValue={String(selected?.title ?? "")} className={inputClass} /></Field><Field label="URL slug"><input name="slug" required defaultValue={String(selected?.slug ?? "")} className={inputClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Category"><input name="category" required defaultValue={String(selected?.category ?? "News")} className={inputClass} /></Field><Field label="Author"><input name="authorName" required defaultValue={String(selected?.authorName ?? "TAP Church")} className={inputClass} /></Field></div><Field label="Excerpt"><textarea name="excerpt" required defaultValue={String(selected?.excerpt ?? "")} className={textareaClass} /></Field><Field label="Article body"><textarea name="body" required defaultValue={String(selected?.body ?? "")} className="min-h-52 mt-1.5 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none focus:border-[#0b4ab8]" /></Field><Field label="Publish date"><input name="publishedAt" type="datetime-local" defaultValue={toInputDate(selected?.publishedAt)} className={inputClass} /></Field><PublishToggle checked={selected?.isPublished === true} /><SaveButton pending={save.isPending} label="Save article" /></form></FormShell>;
}

function MinistryEditor({ selected, onDone }: { selected?: Row; onDone: () => void }) {
  const utils = trpc.useUtils(); const save = trpc.content.ministries.save.useMutation();
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); save.mutate({ id: selected?.id, values: { title: String(f.get("title")), slug: String(f.get("slug")), audience: String(f.get("audience")) as "main" | "junior", summary: String(f.get("summary")), description: String(f.get("description")), leaderName: String(f.get("leaderName") || ""), leaderRole: String(f.get("leaderRole") || ""), meetingInfo: String(f.get("meetingInfo") || ""), heroImageUrl: "", isPublished: f.get("isPublished") === "on" } }, { onSuccess: () => { void utils.content.admin.all.invalidate(); void utils.content.admin.summary.invalidate(); toast.success("Ministry page saved."); onDone(); }, onError: error => toast.error(error.message) }); };
  return <FormShell title={selected ? "Edit ministry page" : "New ministry page"} onCancel={onDone} error={save.error?.message}><form onSubmit={submit} className="grid gap-4"><Field label="Ministry name"><input name="title" required defaultValue={String(selected?.title ?? "")} className={inputClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="URL slug"><input name="slug" required defaultValue={String(selected?.slug ?? "")} className={inputClass} /></Field><Field label="Audience"><select name="audience" defaultValue={String(selected?.audience ?? "main")} className={inputClass}><option value="main">Main parish</option><option value="junior">Junior Church</option></select></Field></div><Field label="Short description"><textarea name="summary" required defaultValue={String(selected?.summary ?? "")} className={textareaClass} /></Field><Field label="Full content"><textarea name="description" required defaultValue={String(selected?.description ?? "")} className={textareaClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Leader name"><input name="leaderName" defaultValue={String(selected?.leaderName ?? "")} className={inputClass} /></Field><Field label="Leader role"><input name="leaderRole" defaultValue={String(selected?.leaderRole ?? "")} className={inputClass} /></Field></div><Field label="Meeting information"><input name="meetingInfo" defaultValue={String(selected?.meetingInfo ?? "")} className={inputClass} /></Field><PublishToggle checked={selected?.isPublished === true} /><SaveButton pending={save.isPending} label="Save ministry" /></form></FormShell>;
}

function AnnouncementEditor({ selected, onDone }: { selected?: Row; onDone: () => void }) {
  const utils = trpc.useUtils(); const save = trpc.content.announcements.save.useMutation();
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); save.mutate({ id: selected?.id, values: { title: String(f.get("title")), body: String(f.get("body")), actionLabel: String(f.get("actionLabel") || ""), actionUrl: String(f.get("actionUrl") || ""), isActive: f.get("isActive") === "on", startsAt: f.get("startsAt") ? new Date(String(f.get("startsAt"))) : null, endsAt: f.get("endsAt") ? new Date(String(f.get("endsAt"))) : null } }, { onSuccess: () => { void utils.content.admin.all.invalidate(); toast.success("Announcement saved."); onDone(); }, onError: error => toast.error(error.message) }); };
  return <FormShell title={selected ? "Edit announcement" : "New announcement"} onCancel={onDone} error={save.error?.message}><form onSubmit={submit} className="grid gap-4"><Field label="Title"><input name="title" required defaultValue={String(selected?.title ?? "")} className={inputClass} /></Field><Field label="Message"><textarea name="body" required defaultValue={String(selected?.body ?? "")} className={textareaClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Button label"><input name="actionLabel" defaultValue={String(selected?.actionLabel ?? "")} className={inputClass} /></Field><Field label="Button link"><input name="actionUrl" type="url" defaultValue={String(selected?.actionUrl ?? "")} className={inputClass} /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Start"><input name="startsAt" type="datetime-local" defaultValue={toInputDate(selected?.startsAt)} className={inputClass} /></Field><Field label="End"><input name="endsAt" type="datetime-local" defaultValue={toInputDate(selected?.endsAt)} className={inputClass} /></Field></div><PublishToggle name="isActive" text="Announcement active" checked={selected?.isActive !== false} /><SaveButton pending={save.isPending} label="Save announcement" /></form></FormShell>;
}

function MediaEditor({ onDone }: { onDone: () => void }) {
  const utils = trpc.useUtils(); const upload = trpc.content.media.upload.useMutation(); const cloudinary = trpc.content.media.cloudinaryStatus.useQuery(); const verifyCloudinary = trpc.content.media.verifyCloudinary.useMutation({ onSuccess: result => toast.success(result.message), onError: error => toast.error(error.message) }); const [file, setFile] = useState<File | null>(null);
  const onFile = (event: ChangeEvent<HTMLInputElement>) => setFile(event.target.files?.[0] ?? null);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!cloudinary.data?.configured) { toast.error("Cloudinary is not configured. Add the three Cloudinary variables in Render first."); return; } if (!file) { toast.error("Choose a file to upload."); return; } const f = new FormData(event.currentTarget); const reader = new FileReader(); reader.onload = () => upload.mutate({ title: String(f.get("title")), altText: String(f.get("altText") || ""), mediaType: String(f.get("mediaType")) as "image" | "video" | "document", filename: file.name, mimeType: file.type || "application/octet-stream", dataUrl: String(reader.result), isPublished: f.get("isPublished") === "on" }, { onSuccess: () => { void utils.content.admin.all.invalidate(); void utils.content.admin.summary.invalidate(); toast.success("Media uploaded to Cloudinary."); onDone(); }, onError: error => toast.error(error.message) }); reader.onerror = () => toast.error("The selected file could not be read."); reader.readAsDataURL(file); };
  return <FormShell title="Upload media asset" onCancel={onDone} error={upload.error?.message}><form onSubmit={submit} className="grid gap-4"><div className={`rounded-xl border p-4 text-sm ${cloudinary.data?.configured ? "border-emerald-100 bg-emerald-50 text-emerald-800" : "border-amber-100 bg-amber-50 text-amber-800"}`}><p className="font-extrabold">Cloudinary {cloudinary.data?.configured ? "is configured" : "needs configuration"}.</p><p className="mt-1 text-xs leading-5">{cloudinary.data?.configured ? `Connected to the ${cloudinary.data.cloudName} cloud. Verify it before the first upload.` : "Add CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, and CLOUDINARY_API_SECRET in Render."}</p>{cloudinary.data?.configured && <Button type="button" variant="outline" disabled={verifyCloudinary.isPending} onClick={() => verifyCloudinary.mutate()} className="mt-3 h-8 rounded-lg border-emerald-200 bg-white text-xs font-extrabold text-emerald-800">{verifyCloudinary.isPending ? "Verifying…" : "Verify connection"}</Button>}</div><Field label="Title"><input name="title" required className={inputClass} /></Field><Field label="Alt text"><input name="altText" className={inputClass} /></Field><Field label="Asset type"><select name="mediaType" className={inputClass}><option value="image">Image</option><option value="video">Video</option><option value="document">Document</option></select></Field><Field label="File"><input name="file" type="file" required onChange={onFile} className="mt-1.5 block w-full text-sm text-slate-600 file:mr-4 file:rounded-lg file:border-0 file:bg-blue-50 file:px-3 file:py-2 file:text-xs file:font-extrabold file:text-[#0b4ab8]" /></Field><PublishToggle checked={false} /><SaveButton pending={upload.isPending} label={file ? `Upload ${file.name}` : "Upload asset"} /></form></FormShell>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className={labelClass}>{label}{children}</label>; }
function PublishToggle({ checked, name = "isPublished", text = "Publish on the public website" }: { checked: boolean; name?: string; text?: string }) { return <label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-xs font-extrabold text-slate-600"><input name={name} defaultChecked={checked} type="checkbox" className="h-4 w-4 accent-[#0b4ab8]" />{text}</label>; }
function SaveButton({ pending, label }: { pending: boolean; label: string }) { return <Button type="submit" disabled={pending} className="mt-2 h-10 rounded-xl bg-[#0b4ab8] text-xs font-extrabold hover:bg-[#063887]">{pending && <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" />}{label}</Button>; }
