import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const roles = ["worker", "ministry_leader", "editor", "admin"] as const;
export default function Approvals() { return <DashboardLayout><ApprovalWorkspace /></DashboardLayout>; }
function ApprovalWorkspace() {
  const { user, loading } = useAuth(); const utils = trpc.useUtils();
  const requests = trpc.account.requests.list.useQuery(undefined, { enabled: user?.role === "master_admin" });
  const decide = trpc.account.requests.decide.useMutation({ onSuccess: () => { void requests.refetch(); void utils.auth.me.invalidate(); toast.success("Access request updated."); } });
  if (loading) return null;
  if (user?.role !== "master_admin") return <section className="mx-auto max-w-2xl py-16"><p className="eyebrow text-[#0b4ab8]">TAP access control</p><h1 className="display mt-4 text-5xl text-[#10213e]">Master Admin only.</h1><p className="mt-5 text-sm leading-7 text-slate-600">Only the Master Admin can review and decide staff access requests.</p></section>;
  return <section className="mx-auto max-w-5xl py-6"><p className="eyebrow text-[#0b4ab8]">Master Admin</p><h1 className="display mt-4 text-5xl text-[#10213e]">Access requests</h1><p className="mt-4 text-sm leading-7 text-slate-600">Approve workers with the correct role, or reject requests that need more information.</p><div className="mt-8 grid gap-4">{requests.isLoading ? <div className="h-32 animate-pulse rounded-2xl bg-slate-200" /> : !requests.data?.length ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-7 text-sm text-slate-600">There are no pending staff access requests.</div> : requests.data.map(request => <RequestCard key={request.id} request={request} pending={decide.isPending} onDecide={(decision, role, note) => decide.mutate({ id: request.id, decision, role, note })} />)}</div></section>;
}
function RequestCard({ request, pending, onDecide }: { request: { id: string; name: string; email: string; requestedRole: string | null; requestNote: string | null }; pending: boolean; onDecide: (decision: "approve" | "reject", role?: (typeof roles)[number], note?: string) => void }) { const [role, setRole] = useState<(typeof roles)[number]>((request.requestedRole as (typeof roles)[number]) ?? "worker"); const [note, setNote] = useState(""); return <article className="rounded-[1.4rem] border border-slate-200 bg-white p-6"><div className="flex gap-4"><ShieldCheck className="h-6 w-6 text-[#0b4ab8]" /><div><h2 className="font-extrabold text-[#10213e]">{request.name}</h2><p className="mt-1 text-sm text-slate-500">{request.email} · requested {request.requestedRole?.replaceAll("_", " ")}</p>{request.requestNote && <p className="mt-4 text-sm leading-6 text-slate-600">“{request.requestNote}”</p>}</div></div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_1.5fr_auto_auto]"><select value={role} onChange={event => setRole(event.target.value as (typeof roles)[number])} className="h-10 rounded-xl border border-slate-200 px-3 text-sm"><option value="worker">Worker</option><option value="ministry_leader">Ministry Leader</option><option value="editor">Editor</option><option value="admin">Admin</option></select><input value={note} onChange={event => setNote(event.target.value)} placeholder="Optional decision note" className="h-10 rounded-xl border border-slate-200 px-3 text-sm" /><Button disabled={pending} onClick={() => onDecide("approve", role, note)} className="h-10 rounded-xl bg-[#0b4ab8] text-xs font-extrabold">Approve</Button><Button disabled={pending} variant="outline" onClick={() => onDecide("reject", undefined, note)} className="h-10 rounded-xl border-rose-200 text-xs font-extrabold text-rose-700">Reject</Button></div></article>; }
