import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { juniorCategoryOptions } from "@/lib/memberOptions";
import { ArrowLeft, BookOpenCheck, HeartHandshake, Loader2, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect } from "react";
import { Link, useLocation } from "wouter";

export default function FamilyHub() {
  const { user, loading, error, refresh } = useAuth({ redirectOnUnauthenticated: true, redirectPath: "/sign-in" });
  const [, setLocation] = useLocation();
  const profile = trpc.account.profile.get.useQuery(undefined, { enabled: user?.role === "member" });
  useEffect(() => { if (user && user.role !== "member") setLocation("/admin"); }, [setLocation, user]);
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#251151]"><Loader2 className="h-6 w-6 animate-spin text-[#baff3c]" /></div>;
  if (error || profile.error) return <div className="grid min-h-screen place-items-center bg-[#251151] p-5 text-center text-white"><div><p className="text-xl font-extrabold">We could not open the Family Hub.</p><button className="mt-4 rounded-xl bg-white px-4 py-2 text-sm font-extrabold text-[#251151]" onClick={() => void refresh()}>Retry</button></div></div>;
  if (!user || user.role !== "member") return null;
  const categories = (profile.data?.juniorAgeCategories ?? []).map(value => juniorCategoryOptions.find(option => option.value === value)?.label).filter(Boolean);
  return <main className="min-h-screen bg-[#251151] text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/member" className="inline-flex items-center gap-2 text-sm font-extrabold"><ArrowLeft className="h-4 w-4" />My Parish</Link><Link href="/junior-church" className="text-xs font-extrabold text-[#baff3c]">Junior Church</Link></div></header><section className="mx-auto max-w-6xl px-5 py-12"><p className="eyebrow text-[#baff3c]">Junior Church Family Hub</p><h1 className="display mt-5 max-w-2xl text-6xl leading-[0.88]">Faith moments for your family.</h1><p className="mt-6 max-w-2xl text-sm leading-7 text-violet-100">A safeguarded parent and guardian space for family resources, Junior Church updates, and age-category guidance. No child profiles or direct child accounts are created here.</p><div className="mt-10 grid gap-4 md:grid-cols-3"><FamilyCard icon={<Sparkles />} title="Your family categories" copy={categories.length ? categories.join(" · ") : "Choose the Junior Church groups relevant to your family."} action="Update preferences" href="/member#preferences" /><FamilyCard icon={<BookOpenCheck />} title="Weekly faith moments" copy="Use a short conversation starter, a memory-verse moment, or a prayer prompt at home." action="Explore Junior Church" href="/junior-church" /><FamilyCard icon={<HeartHandshake />} title="Family support" copy="Need prayer or clarity about a Junior Church activity? Contact the parish team through the website." action="Ask for prayer" href="/#prayer-request" /></div><section className="mt-10 rounded-[1.7rem] bg-white p-7 text-[#251151] sm:p-9"><p className="eyebrow text-[#7c1eff]">What comes next</p><h2 className="mt-4 text-3xl font-extrabold">Built around your family, not a public child profile.</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><MiniStep number="01" title="Select categories" copy="Tell us the age groups relevant to your household." /><MiniStep number="02" title="See relevant resources" copy="Find age-aware guidance, event details, and family moments." /><MiniStep number="03" title="Stay connected" copy="Receive only the updates you have asked the parish to share." /></div></section></section></main>;
}
function FamilyCard({ icon, title, copy, action, href }: { icon: React.ReactNode; title: string; copy: string; action: string; href: string }) { return <article className="rounded-[1.5rem] border border-white/15 bg-white/10 p-6"><div className="text-[#baff3c]">{icon}</div><h2 className="mt-6 text-xl font-extrabold">{title}</h2><p className="mt-3 min-h-14 text-sm leading-6 text-violet-100">{copy}</p><Link href={href} className="mt-6 inline-flex text-sm font-extrabold text-[#baff3c]">{action} →</Link></article>; }
function MiniStep({ number, title, copy }: { number: string; title: string; copy: string }) { return <div className="rounded-2xl bg-violet-50 p-5"><p className="text-xs font-black tracking-[0.14em] text-[#7c1eff]">{number}</p><h3 className="mt-5 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></div>; }
