import { ArrowRight, BookOpenCheck, HeartHandshake, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { Link } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { juniorGroups } from "@/data/site";

const palette: Record<string, string> = { orange: "bg-orange-300 text-[#3b155e]", lime: "bg-lime-300 text-[#193a17]", pink: "bg-pink-300 text-[#5c164f]", sky: "bg-sky-300 text-[#082d53]", purple: "bg-violet-300 text-[#2f175f]" };

export default function JuniorChurch() {
  return <PublicLayout><section className="junior-surface junior-grid overflow-hidden"><div className="container relative min-h-[39rem] py-16 sm:min-h-[44rem] sm:py-24"><div className="absolute right-[4%] top-12 float-slow grid h-44 w-44 rotate-12 place-items-center rounded-[2rem] bg-[#baff3c] text-center text-[#251151] shadow-2xl sm:h-60 sm:w-60"><span className="display text-4xl leading-none sm:text-6xl">JUNIOR<br />CHURCH</span></div><div className="relative max-w-2xl pt-24 sm:pt-16"><p className="eyebrow text-[#baff3c]">A world within RCCG TAP</p><h1 className="display mt-5 text-6xl leading-[0.86] text-white sm:text-8xl">Big faith.<br /><span className="text-pink-300">Bright life.</span></h1><p className="mt-7 max-w-md text-base leading-7 text-violet-100">RCCG TAP Junior Church is an age-aware space for children and teens to ask honest questions, build friendships, and know Jesus for themselves—with parent and guardian support at the centre.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#age-groups" className="tap-button inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-extrabold text-[#2a1456]">Explore age groups <ArrowRight className="h-4 w-4" /></a><Link href="/visit" className="tap-button inline-flex items-center gap-2 rounded-full border border-white/40 px-5 py-3 text-sm font-extrabold text-white">Plan a family visit</Link></div></div><div className="absolute bottom-8 left-0 flex items-center gap-2 text-xs font-extrabold text-violet-200"><Sparkles className="h-4 w-4 text-[#baff3c]" />A safeguarded, engaging space for every age.</div></div></section>
    <section id="age-groups" className="bg-[#fffdf7] py-20 sm:py-28"><div className="container"><div className="max-w-2xl"><p className="eyebrow text-[#7c1eff]">Choose your space</p><h2 className="display mt-5 text-5xl leading-[0.94] text-[#21104b]">Same family. A little more you.</h2><p className="mt-5 text-sm leading-7 text-slate-600">Every age group has a clear place to grow. Parents and guardians can later personalise their household’s family experience from one secure Family Hub.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{juniorGroups.map((group, index) => <article key={group.name} className={`min-h-60 rounded-[1.55rem] p-6 ${palette[group.accent]}`}><p className="text-xs font-black tracking-[0.14em]">0{index + 1} · {group.age}</p><h3 className="display mt-14 text-4xl leading-[0.9]">{group.name}</h3><p className="mt-4 text-sm font-semibold leading-6 opacity-80">{group.line}</p></article>)}</div></div></section>
    <section className="bg-[#f6f1ff] py-20"><div className="container grid gap-5 md:grid-cols-3"><Feature icon={<BookOpenCheck />} title="For parents & guardians" copy="Choose age categories, find family guidance, and stay connected to relevant Junior Church updates." /><Feature icon={<ShieldCheck />} title="Safeguarding-first" copy="The Family Hub uses guardian preferences only. It does not create public child profiles, direct child accounts, or open messaging." /><Feature icon={<UsersRound />} title="For volunteers" copy="Approved leaders and volunteers can receive clear, staff-managed guidance through the parish’s secure workflows." /></div></section>
    <section className="junior-surface py-16"><div className="container flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="eyebrow text-[#baff3c]">For parents & guardians</p><h2 className="display mt-4 text-4xl text-white">Ready to personalise your family journey?</h2><p className="mt-3 max-w-xl text-sm leading-7 text-violet-100">Sign in to choose your family’s Junior Church category preferences and view the resources intended for your household.</p></div><Link href="/family-hub" className="tap-button inline-flex shrink-0 items-center gap-2 rounded-full bg-[#baff3c] px-5 py-3 text-sm font-extrabold text-[#251151]">Open Family Hub <ArrowRight className="h-4 w-4" /></Link></div></section>
  </PublicLayout>;
}
function Feature({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <article className="rounded-[1.5rem] bg-white p-6"><div className="text-[#7c1eff]">{icon}</div><h2 className="mt-6 text-xl font-extrabold text-[#21104b]">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{copy}</p>{title === "For volunteers" && <Link href="/sign-in" className="mt-6 inline-flex text-sm font-extrabold text-[#7c1eff]">Request staff access →</Link>}</article>; }
