import { ArrowRight, Sparkles } from "lucide-react";
import { Link } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { juniorGroups } from "@/data/site";

const palette: Record<string, string> = { orange: "bg-orange-300 text-[#3b155e]", lime: "bg-lime-300 text-[#193a17]", pink: "bg-pink-300 text-[#5c164f]", sky: "bg-sky-300 text-[#082d53]", purple: "bg-violet-300 text-[#2f175f]" };

export default function JuniorChurch() {
  return <PublicLayout><section className="junior-surface junior-grid overflow-hidden"><div className="container relative min-h-[37rem] py-16 sm:min-h-[43rem] sm:py-24"><div className="absolute right-[4%] top-12 float-slow grid h-44 w-44 rotate-12 place-items-center rounded-[2rem] bg-[#baff3c] text-center text-[#251151] shadow-2xl sm:h-60 sm:w-60"><span className="display text-4xl leading-none sm:text-6xl">JUNIOR<br />CHURCH</span></div><div className="relative max-w-2xl pt-24 sm:pt-16"><p className="eyebrow text-[#baff3c]">A world within TAP</p><h1 className="display mt-5 text-6xl leading-[0.86] text-white sm:text-8xl">Big faith.<br /><span className="text-pink-300">Bright life.</span></h1><p className="mt-7 max-w-md text-base leading-7 text-violet-100">TAP Junior Church is a joyful, age-aware space for children and teens to ask honest questions, build great friendships, and know Jesus for themselves.</p><Link href="/visit" className="tap-button mt-8 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-extrabold text-[#2a1456]">Plan a family visit<ArrowRight className="h-4 w-4" /></Link></div><div className="absolute bottom-8 left-0 flex items-center gap-2 text-xs font-extrabold text-violet-200"><Sparkles className="h-4 w-4 text-[#baff3c]" />A safe, engaging space for every age.</div></div></section><section className="bg-[#fffdf7] py-20 sm:py-28"><div className="container"><div className="max-w-2xl"><p className="eyebrow text-[#7c1eff]">Choose your space</p><h2 className="display mt-5 text-5xl leading-[0.94] text-[#21104b]">Same family. A little more you.</h2></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{juniorGroups.map((group, index) => <article key={group.name} className={`min-h-60 rounded-[1.55rem] p-6 ${palette[group.accent]}`}><p className="text-xs font-black tracking-[0.14em]">0{index + 1} · {group.age}</p><h3 className="display mt-14 text-4xl leading-[0.9]">{group.name}</h3><p className="mt-4 text-sm font-semibold leading-6 opacity-80">{group.line}</p></article>)}</div></div></section><section className="junior-surface py-16"><div className="container grid gap-6 md:grid-cols-3"><div><p className="eyebrow text-[#baff3c]">For parents</p><p className="mt-4 text-sm leading-7 text-violet-100">The Junior Church team can publish arrival guidance, child check-in details, and parent resources here.</p></div><div><p className="eyebrow text-[#baff3c]">For volunteers</p><p className="mt-4 text-sm leading-7 text-violet-100">A clear path for safe, equipped volunteer onboarding will live in this space.</p></div><div><p className="eyebrow text-[#baff3c]">For young people</p><p className="mt-4 text-sm leading-7 text-violet-100">Stories, events, videos, and conversations created with your world in mind.</p></div></div></section></PublicLayout>;
}
