import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { availabilityOptions, juniorCategoryOptions, ministryOptions, type AvailabilityOptionValue, type JuniorCategoryOptionValue, type MinistryOptionValue } from "@/lib/memberOptions";
import { BellRing, CalendarDays, Check, ChevronRight, HeartHandshake, Loader2, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";

type PreferencesDraft = { ministryInterests: MinistryOptionValue[]; serviceAvailability: AvailabilityOptionValue | null; wantsParishUpdates: boolean; isGuardian: boolean; juniorAgeCategories: JuniorCategoryOptionValue[] };
const emptyPreferences: PreferencesDraft = { ministryInterests: [], serviceAvailability: null, wantsParishUpdates: true, isGuardian: false, juniorAgeCategories: [] };

export default function MemberDashboard() {
  const { user, loading, error, refresh, logout } = useAuth({ redirectOnUnauthenticated: true, redirectPath: "/sign-in" });
  const [, setLocation] = useLocation();
  useEffect(() => { if (user && user.role !== "member") setLocation("/admin"); }, [setLocation, user]);
  if (loading) return <LoadingScreen />;
  if (error) return <RecoveryScreen error={error.message} retry={refresh} />;
  if (!user || user.role !== "member") return null;
  return <MemberWorkspace user={user} logout={logout} />;
}

function MemberWorkspace({ user, logout }: { user: { name: string; email: string }; logout: () => void }) {
  const utils = trpc.useUtils();
  const profile = trpc.account.profile.get.useQuery();
  const events = trpc.content.events.list.useQuery();
  const announcements = trpc.content.announcements.list.useQuery();
  const eventInterestIds = trpc.account.memberHub.eventInterestIds.useQuery();
  const memberUpdates = trpc.account.memberHub.updates.useQuery();
  const [name, setName] = useState(user.name);
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [preferences, setPreferences] = useState<PreferencesDraft>(emptyPreferences);

  useEffect(() => setName(user.name), [user.name]);
  useEffect(() => {
    if (!profile.data) return;
    setPreferences({ ministryInterests: profile.data.ministryInterests, serviceAvailability: profile.data.serviceAvailability, wantsParishUpdates: profile.data.wantsParishUpdates, isGuardian: profile.data.isGuardian, juniorAgeCategories: profile.data.juniorAgeCategories });
  }, [profile.data]);

  const updateName = trpc.account.profile.updateName.useMutation({ onSuccess: () => { void utils.auth.me.invalidate(); toast.success("Your name has been updated."); }, onError: error => toast.error(error.message) });
  const changePassword = trpc.account.profile.changePassword.useMutation({ onSuccess: () => { setCurrentPassword(""); setNewPassword(""); toast.success("Your password has been updated."); }, onError: error => toast.error(error.message) });
  const savePreferences = trpc.account.profile.savePreferences.useMutation({ onSuccess: () => { void utils.account.profile.get.invalidate(); toast.success("Your parish preferences have been saved."); }, onError: error => toast.error(error.message) });
  const setEventInterest = trpc.account.memberHub.setEventInterest.useMutation({ onSuccess: () => void utils.account.memberHub.eventInterestIds.invalidate(), onError: error => toast.error(error.message) });

  const upcomingEvents = useMemo(() => (events.data ?? []).filter(event => new Date(event.startsAt).getTime() >= Date.now()).slice(0, 3), [events.data]);
  const interestedIds = new Set(eventInterestIds.data ?? []);
  const onboardingComplete = Boolean(profile.data?.onboardingCompletedAt);
  const toggleMinistryInterest = (value: MinistryOptionValue) => setPreferences(current => ({ ...current, ministryInterests: current.ministryInterests.includes(value) ? current.ministryInterests.filter(item => item !== value) : [...current.ministryInterests, value] }));
  const toggleJuniorCategory = (value: JuniorCategoryOptionValue) => setPreferences(current => ({ ...current, juniorAgeCategories: current.juniorAgeCategories.includes(value) ? current.juniorAgeCategories.filter(item => item !== value) : [...current.juniorAgeCategories, value] }));

  return <main className="min-h-screen bg-[#f7f9fd] text-[#10213e]">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-5"><Link href="/" className="text-sm font-extrabold">RCCG TAP</Link><div className="flex items-center gap-3"><Link href="/" className="text-xs font-extrabold text-[#0b4ab8]">Public website</Link><Button variant="outline" onClick={() => void logout()} className="h-9 rounded-full text-xs">Sign out</Button></div></div></header>
    <section className="mx-auto max-w-6xl px-5 py-10 sm:py-14">
      <div className="relative overflow-hidden rounded-[2rem] bg-[#10213e] px-6 py-9 text-white sm:px-10"><Sparkles className="absolute right-8 top-7 h-8 w-8 text-[#d7ff54]" /><p className="eyebrow text-[#d7ff54]">My Parish</p><h1 className="display mt-4 max-w-2xl text-5xl leading-none">Welcome back, {user.name}.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-blue-100">A personal place for parish updates, ministry interests, family resources, and the next meaningful step in your journey at RCCG TAP.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="#preferences" className="tap-button rounded-full bg-[#d7ff54] px-4 py-2.5 text-xs font-extrabold text-[#10213e]">{onboardingComplete ? "Update my preferences" : "Complete my parish profile"}</Link><Link href="/family-hub" className="tap-button rounded-full border border-white/30 px-4 py-2.5 text-xs font-extrabold text-white">Family hub <ChevronRight className="inline h-3.5 w-3.5" /></Link></div></div>

      <div className="mt-7 grid gap-4 md:grid-cols-3"><QuickLink href="/announcements" icon={<BellRing className="h-5 w-5" />} title="Parish updates" copy={`${announcements.data?.length ?? 0} current updates and notices.`} /><QuickLink href="/events" icon={<CalendarDays className="h-5 w-5" />} title="Plan ahead" copy="Save interest for events you want to attend." /><QuickLink href="/#prayer-request" icon={<HeartHandshake className="h-5 w-5" />} title="Prayer support" copy="Share a confidential request with the prayer team." dark /></div>

      <div className="mt-10 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
        <section className="rounded-[1.6rem] border border-slate-200 bg-white p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-[#0b4ab8]">Your next moments</p><h2 className="mt-3 text-2xl font-extrabold">Upcoming at RCCG TAP</h2></div><Link href="/events" className="text-xs font-extrabold text-[#0b4ab8]">Full calendar</Link></div><div className="mt-6 grid gap-3">{upcomingEvents.length ? upcomingEvents.map(event => { const interested = interestedIds.has(event.id); return <article key={event.id} className="flex flex-col justify-between gap-4 rounded-2xl bg-slate-50 p-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold text-[#0b4ab8]">{new Date(event.startsAt).toLocaleDateString(undefined, { weekday: "short", month: "short", day: "numeric" })}</p><h3 className="mt-1 font-extrabold">{event.title}</h3><p className="mt-1 text-xs text-slate-500">{event.location}</p></div><div className="flex gap-2"><Link href={`/events/${event.slug}`} className="inline-flex h-9 items-center rounded-xl border border-slate-200 px-3 text-xs font-extrabold">Details</Link><Button disabled={setEventInterest.isPending} onClick={() => setEventInterest.mutate({ eventId: event.id, interested: !interested })} className={`h-9 rounded-xl px-3 text-xs font-extrabold ${interested ? "bg-emerald-600 hover:bg-emerald-700" : "bg-[#0b4ab8]"}`}>{interested && <Check className="mr-1 h-3.5 w-3.5" />}{interested ? "Interested" : "I’m interested"}</Button></div></article>; }) : <p className="rounded-2xl bg-slate-50 p-5 text-sm leading-6 text-slate-600">New parish events will appear here as they are published.</p>}</div></section>
        <section className="rounded-[1.6rem] bg-[#d7ff54] p-6 sm:p-8"><UsersRound className="h-7 w-7" /><p className="eyebrow mt-6 text-[#405223]">Ministry connection</p><h2 className="mt-3 text-2xl font-extrabold">Find your place to serve.</h2><p className="mt-3 text-sm leading-6 text-[#32451c]">Tell us where you are interested. This is a preference, not an automatic staff or ministry assignment.</p><Link href="/member/ministry" className="mt-6 inline-flex items-center gap-1 text-sm font-extrabold underline underline-offset-4">Explore Ministry Hub <ChevronRight className="h-4 w-4" /></Link></section>
      </div>

      <section className="mt-10 rounded-[1.7rem] bg-[#eef5ff] p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow text-[#0b4ab8]">Matched for you</p><h2 className="mt-3 text-3xl font-extrabold">Relevant parish notes.</h2><p className="mt-3 text-sm leading-6 text-slate-600">Updates shown here are matched to the preferences you have chosen in My Parish.</p></div><BellRing className="h-6 w-6 text-[#0b4ab8]" /></div><div className="mt-6 grid gap-3 md:grid-cols-2">{memberUpdates.isLoading ? <div className="rounded-2xl bg-white p-5"><Loader2 className="h-5 w-5 animate-spin text-[#0b4ab8]" /></div> : memberUpdates.data?.length ? memberUpdates.data.slice(0, 4).map(update => <article key={update.id} className="rounded-2xl bg-white p-5"><h3 className="font-extrabold">{update.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{update.body}</p><p className="mt-4 text-xs font-bold text-[#0b4ab8]">{new Date(update.createdAt).toLocaleDateString()}</p></article>) : <div className="rounded-2xl bg-white p-5 text-sm leading-6 text-slate-600">As you choose ministry or family preferences, relevant parish notes can appear here.</div>}</div></section>

      <section id="preferences" className="mt-10 rounded-[1.7rem] border border-slate-200 bg-white p-6 sm:p-8"><div className="max-w-2xl"><p className="eyebrow text-[#0b4ab8]">Your parish profile</p><h2 className="mt-3 text-3xl font-extrabold">Make your dashboard feel like yours.</h2><p className="mt-3 text-sm leading-6 text-slate-600">Choose what you are interested in and, if you are a parent or guardian, the Junior Church groups you want family resources for. We do not create child accounts or store children’s names here.</p></div><div className="mt-7 grid gap-8 lg:grid-cols-[1fr_0.9fr]"><div><ChoiceGroup title="Ministry interests" options={ministryOptions} selected={preferences.ministryInterests} onToggle={toggleMinistryInterest} /><div className="mt-6"><p className="text-sm font-extrabold">When are you usually available?</p><div className="mt-3 flex flex-wrap gap-2">{availabilityOptions.map(option => <button type="button" key={option.value} onClick={() => setPreferences(current => ({ ...current, serviceAvailability: current.serviceAvailability === option.value ? null : option.value }))} className={`rounded-full border px-3 py-2 text-xs font-extrabold ${preferences.serviceAvailability === option.value ? "border-[#0b4ab8] bg-blue-50 text-[#0b4ab8]" : "border-slate-200 text-slate-600"}`}>{option.label}</button>)}</div></div><label className="mt-6 flex items-start gap-3 rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-700"><input type="checkbox" checked={preferences.wantsParishUpdates} onChange={event => setPreferences(current => ({ ...current, wantsParishUpdates: event.target.checked }))} className="mt-1 h-4 w-4 accent-[#0b4ab8]" />I would like to receive parish updates that are relevant to my interests.</label></div><div className="rounded-[1.4rem] bg-[#f6f1ff] p-5"><label className="flex items-start gap-3 text-sm leading-6 text-[#39255e]"><input type="checkbox" checked={preferences.isGuardian} onChange={event => setPreferences(current => ({ ...current, isGuardian: event.target.checked, juniorAgeCategories: event.target.checked ? current.juniorAgeCategories : [] }))} className="mt-1 h-4 w-4 accent-[#7c1eff]" /><span><strong className="block">I am a parent or guardian</strong>Select Junior Church category preferences for family resources and notices.</span></label>{preferences.isGuardian && <div className="mt-5"><ChoiceGroup title="Junior Church categories" options={juniorCategoryOptions} selected={preferences.juniorAgeCategories} onToggle={toggleJuniorCategory} compact /></div>}</div></div><Button onClick={() => savePreferences.mutate(preferences)} disabled={savePreferences.isPending} className="mt-8 h-11 rounded-xl bg-[#0b4ab8] px-5 text-xs font-extrabold">{savePreferences.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Saving preferences…</> : "Save my parish profile"}</Button></section>

      <div className="mt-10 grid gap-5 lg:grid-cols-2"><section className="rounded-[1.5rem] border border-slate-200 bg-white p-7"><p className="font-extrabold">Personal details</p><p className="mt-2 text-sm text-slate-500">{user.email}</p><form className="mt-5 grid gap-3" onSubmit={event => { event.preventDefault(); updateName.mutate({ name }); }}><label className="grid gap-1.5 text-xs font-bold text-slate-600">Display name<input required value={name} onChange={event => setName(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm" /></label><Button disabled={updateName.isPending || name.trim() === user.name} className="h-11 rounded-xl bg-[#0b4ab8] text-xs font-extrabold">Save name</Button></form></section><section className="rounded-[1.5rem] border border-slate-200 bg-white p-7"><p className="font-extrabold">Change password</p><p className="mt-2 text-sm leading-6 text-slate-600">Use at least 10 characters and keep your password private.</p><form className="mt-5 grid gap-3" onSubmit={event => { event.preventDefault(); changePassword.mutate({ currentPassword, newPassword }); }}><label className="grid gap-1.5 text-xs font-bold text-slate-600">Current password<input required type="password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm" /></label><label className="grid gap-1.5 text-xs font-bold text-slate-600">New password<input required minLength={10} type="password" value={newPassword} onChange={event => setNewPassword(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm" /></label><Button disabled={changePassword.isPending || !currentPassword || newPassword.length < 10} className="h-11 rounded-xl bg-[#0b4ab8] text-xs font-extrabold">Update password</Button></form></section></div>
    </section>
  </main>;
}

function ChoiceGroup<T extends string>({ title, options, selected, onToggle, compact = false }: { title: string; options: readonly { value: T; label: string }[]; selected: T[]; onToggle: (value: T) => void; compact?: boolean }) { return <div><p className="text-sm font-extrabold">{title}</p><div className={`mt-3 grid gap-2 ${compact ? "sm:grid-cols-2" : "sm:grid-cols-2"}`}>{options.map(option => <button key={option.value} type="button" onClick={() => onToggle(option.value)} className={`flex items-center justify-between rounded-xl border px-3 py-3 text-left text-xs font-bold ${selected.includes(option.value) ? "border-[#0b4ab8] bg-blue-50 text-[#0b4ab8]" : "border-slate-200 text-slate-600 hover:bg-slate-50"}`}><span>{option.label}</span>{selected.includes(option.value) && <Check className="h-4 w-4" />}</button>)}</div></div>; }
function QuickLink({ href, icon, title, copy, dark = false }: { href: string; icon: React.ReactNode; title: string; copy: string; dark?: boolean }) { return <Link href={href} className={`rounded-[1.4rem] p-5 transition hover:-translate-y-1 hover:shadow-lg ${dark ? "bg-[#10213e] text-white" : "border border-slate-200 bg-white"}`}><div className={dark ? "text-[#d7ff54]" : "text-[#0b4ab8]"}>{icon}</div><h2 className="mt-5 font-extrabold">{title}</h2><p className={`mt-2 text-sm leading-6 ${dark ? "text-blue-100" : "text-slate-600"}`}>{copy}</p></Link>; }
function LoadingScreen() { return <div className="grid min-h-screen place-items-center bg-slate-50"><div className="grid justify-items-center gap-4"><Loader2 className="h-6 w-6 animate-spin text-[#0b4ab8]" /><p className="text-sm font-bold text-slate-600">Opening your member dashboard…</p></div></div>; }
function RecoveryScreen({ error, retry }: { error: string; retry: () => Promise<unknown> }) { return <main className="grid min-h-screen place-items-center bg-slate-50 px-5"><section className="max-w-md rounded-[1.5rem] border border-slate-200 bg-white p-8 text-center shadow-sm"><ShieldCheck className="mx-auto h-7 w-7 text-[#0b4ab8]" /><p className="eyebrow mt-5 text-[#0b4ab8]">Member dashboard</p><h1 className="mt-4 text-2xl font-extrabold">We could not open your dashboard.</h1><p className="mt-3 text-sm leading-6 text-slate-600">{error || "Please check your connection and try again."}</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Button onClick={() => void retry()} className="rounded-xl bg-[#0b4ab8]">Retry dashboard</Button><Link href="/sign-in" className="inline-flex h-10 items-center rounded-xl border border-slate-200 px-4 text-sm font-extrabold">Sign in</Link></div></section></main>; }
