import { ArrowRight, CheckCircle2, MapPin } from "lucide-react";
import { Link } from "wouter";
import { PageHero } from "@/components/PageBits";
import PublicLayout from "@/components/PublicLayout";
import { serviceSchedule, site } from "@/data/site";

export default function Visit() {
  return <PublicLayout><PageHero eyebrow="Plan a visit" title="Your first Sunday, made simple." copy="We would love to welcome you to TAP Church. Come as you are, find a seat, and let us know how we can help you feel at home." extra={<div className="inline-flex items-center gap-2 text-sm font-bold text-[#d7ff54]"><MapPin className="h-4 w-4" />{site.city}</div>} /><section className="container grid gap-12 py-20 sm:py-28 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="eyebrow text-[#0b4ab8]">Before you arrive</p><h2 className="display mt-5 text-5xl leading-[0.95] text-[#10213e]">A warm welcome awaits.</h2><p className="mt-5 text-sm leading-7 text-slate-600">TAP Church meets in Ibadan, Nigeria. Campus directions, service times, and contact details will be confirmed here by the parish office.</p><div className="mt-8 rounded-[1.4rem] border border-blue-100 bg-blue-50 p-6"><p className="font-extrabold text-[#10213e]">Location context</p><p className="mt-2 text-sm leading-6 text-slate-600">{site.address}</p><p className="mt-4 text-xs font-bold text-[#0b4ab8]">Exact campus directions are being prepared.</p></div></div><div className="rounded-[1.5rem] border border-slate-200 bg-white p-7"><p className="eyebrow text-[#0b4ab8]">What to expect</p><div className="mt-6 grid gap-5">{["A friendly team ready to welcome you.", "Worship and Bible teaching for every season of life.", "Dedicated spaces for children and teens through Junior Church.", "A clear next step if you would like to make TAP home."].map(item => <p key={item} className="flex gap-3 text-sm leading-6 text-slate-700"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#0b4ab8]" />{item}</p>)}</div><Link href="/contact" className="tap-button mt-8 inline-flex items-center gap-2 rounded-full bg-[#0b4ab8] px-5 py-3 text-sm font-extrabold text-white">Ask a question<ArrowRight className="h-4 w-4" /></Link></div></section><section className="border-y border-slate-200 bg-white py-20"><div className="container"><p className="eyebrow text-[#0b4ab8]">Weekly schedule</p><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{serviceSchedule.map(service => <div key={service.name} className="rounded-2xl border border-slate-200 p-5"><p className="font-extrabold text-[#10213e]">{service.name}</p><p className="mt-2 text-sm font-semibold text-[#0b4ab8]">{service.time}</p></div>)}</div></div></section></PublicLayout>;
}
