import { HeartHandshake, Loader2 } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

export default function PrayerRequestForm() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [request, setRequest] = useState(""); const [wantsFollowUp, setWantsFollowUp] = useState(false);
  const submit = trpc.prayer.submit.useMutation({ onSuccess: () => { setName(""); setEmail(""); setRequest(""); setWantsFollowUp(false); toast.success("Your prayer request has been received with care."); }, onError: error => toast.error(error.message) });
  const onSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); submit.mutate({ name: name || undefined, email: email || undefined, request, wantsFollowUp }); };
  return <section id="prayer-request" className="bg-[#10213e] py-20 text-white sm:py-28"><div className="container grid gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:items-start"><div><HeartHandshake className="h-8 w-8 text-[#d7ff54]" /><p className="eyebrow mt-7 text-[#d7ff54]">Prayer request</p><h2 className="display mt-5 text-5xl leading-[0.94]">You do not have to carry it alone.</h2><p className="mt-5 max-w-md text-sm leading-7 text-blue-100">Share a prayer need with the parish prayer team. Your request is stored privately and is visible only to authorised administrators.</p></div><form onSubmit={onSubmit} className="rounded-[1.5rem] bg-white p-6 text-[#10213e] sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-xs font-extrabold uppercase tracking-[0.1em] text-slate-500">Name <span className="normal-case font-medium tracking-normal text-slate-400">(optional)</span><input value={name} onChange={event => setName(event.target.value)} className="h-11 rounded-xl border border-slate-200 px-3 text-sm normal-case tracking-normal outline-none focus:border-[#0b4ab8]" /></label><label className="grid gap-1.5 text-xs font-extrabold uppercase tracking-[0.1em] text-slate-500">Email <span className="normal-case font-medium tracking-normal text-slate-400">(optional)</span><input value={email} onChange={event => setEmail(event.target.value)} type="email" className="h-11 rounded-xl border border-slate-200 px-3 text-sm normal-case tracking-normal outline-none focus:border-[#0b4ab8]" /></label></div><label className="mt-4 grid gap-1.5 text-xs font-extrabold uppercase tracking-[0.1em] text-slate-500">Your request<textarea required minLength={10} maxLength={4000} value={request} onChange={event => setRequest(event.target.value)} placeholder="How can we pray with you?" className="min-h-32 rounded-xl border border-slate-200 p-3 text-sm normal-case tracking-normal outline-none focus:border-[#0b4ab8]" /></label><label className="mt-4 flex items-start gap-3 text-sm leading-6 text-slate-600"><input checked={wantsFollowUp} onChange={event => setWantsFollowUp(event.target.checked)} type="checkbox" className="mt-1 h-4 w-4 accent-[#0b4ab8]" />I would welcome a follow-up from the prayer team by email.</label><button disabled={submit.isPending} className="tap-button mt-6 inline-flex h-11 items-center gap-2 rounded-xl bg-[#0b4ab8] px-5 text-sm font-extrabold text-white disabled:opacity-60">{submit.isPending && <Loader2 className="h-4 w-4 animate-spin" />}Send prayer request</button></form></div></section>;
}
